x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '1.8.6'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  images:
    '':
      properties:
        imageFull:
          type: FULL
    odigos-init-container:
      properties:
        initContainerImageFull:
          type: FULL
    odigos-scheduler:
      properties:
        schedulerImageFull:
          type: FULL
    odigos-instrumentor:
      properties:
        instrumentorImageFull:
          type: FULL
    odigos-odiglet:
      properties:
        odigletImageFull:
          type: FULL
    odigos-ui:
      properties:
        uiImageFull:
          type: FULL
    odigos-autoscaler:
      properties:
        autoscalerImageFull:
          type: FULL
    odigos-collector:
      properties:
        collectorImageFull:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

required:
- name
- namespace
